name: Go Checks

on:
  pull_request:
  push:
    branches: ["master","release-v0[0-9][0-9]"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'push' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  go-check:
    uses: pl-strflt/uci/.github/workflows/go-check.yml@v0.0
